# Site settings
title: "Silicon Witchery Docs"
remote_theme: pmarsceill/just-the-docs
description: "Silicon Witchery Technical Documentation"
permalink: pretty
heading_anchors: true

# Plugins
plugins:
  - jekyll-seo-tag

# Header
search_enabled: true
aux_links_new_tab: true
aux_links:
  "Get the hardware":
   - "https://siliconwitchery.com"


# Footer
footer_content: "Copyright &copy; 2020 <a href=\"https://siliconwitchery.com\">Silicon Witchery AB</a>"
last_edit_timestamp: true # Page must have last_modified_date defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Google analytics tracking
# ga_tracking: UA-1234567-89 TODO
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings

# Optimisations
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
