# Site settings
title: "Silicon Witchery Documentation Center"
logo: "/assets/images/site-title.png"
remote_theme: pmarsceill/just-the-docs
description: "Technical documentation for all Silicon Witchery hardware and firmware products."
permalink: pretty
heading_anchors: true
url: "https://docs.siliconwitchery.com"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Header
search_enabled: true
aux_links_new_tab: true
aux_links:
  "Homepage":
   - "https://www.siliconwitchery.com"
  "YouTube":
   - "https://www.youtube.com/channel/UCIThq9I8dlz9rRT46Q0q9qw"
  "GitHub":
   - "https://github.com/siliconwitchery"

# Footer
footer_content: "Copyright &copy; 2022-2025 <a href=\"https://siliconwitchery.com\">Silicon Witchery AB</a> (<a href=\"https://github.com/siliconwitchery/website#privacy-policy\">Privacy policy</a>)"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"

# SEO settings
twitter:
  username: siliconwitchery
  card: summary_large_image
social:
  name: Silicon Witchery
  links:
    - https://twitter.com/siliconwitchery
    - https://www.linkedin.com/company/siliconwitchery/
    - https://github.com/siliconwitchery

# Umami analytics settings
umami_id: 64d2de71-75d2-42a7-a7c2-a870e1acd348

# Mermaid diagrams
mermaid:
  version: "9.2.2" # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/

# Call-outs 
callouts:
  warning:
    title: Caution
    color: red
  note:
    title: Note
    color: blue
    
# Other settings
enable_copy_code_button: true

# Optimizations
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Exclude files from being processed by Jekyll
exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to this site:
  - .vscode/
  - .gitignore
  - CNAME
  - LICENSE.md
  - README.md